from feature_engine.specification import FeatureSpec


CHANCE_CREATION_FEATURES = [
    FeatureSpec(
        id="support_runs",
        domain="chance_creation",
        category="off_ball_runs",
        output_column="support_runs",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"associated_off_ball_run_subtype": "support"},
        description="Counts support runs.",
        interpretation="Measures supporting movement around the ball carrier.",
        status="implemented",
    ),
    FeatureSpec(
        id="overlap_runs",
        domain="chance_creation",
        category="off_ball_runs",
        output_column="overlap_runs",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"associated_off_ball_run_subtype": "overlap"},
        description="Counts overlap runs.",
        interpretation="Measures overlapping attacking movements.",
        status="implemented",
    ),
    FeatureSpec(
        id="underlap_runs",
        domain="chance_creation",
        category="off_ball_runs",
        output_column="underlap_runs",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"associated_off_ball_run_subtype": "underlap"},
        description="Counts underlap runs.",
        interpretation="Measures interior supporting runs.",
        status="implemented",
    ),
    FeatureSpec(
        id="cross_receivers",
        domain="chance_creation",
        category="receiving",
        output_column="cross_receivers",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"associated_off_ball_run_subtype": "cross_receiver"},
        description="Counts cross-receiver movements.",
        interpretation="Measures attacking runs to receive crosses.",
        status="implemented",
    ),
    FeatureSpec(
        id="coming_short_runs",
        domain="chance_creation",
        category="receiving",
        output_column="coming_short_runs",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"associated_off_ball_run_subtype": "coming_short"},
        description="Counts players checking toward the ball.",
        interpretation="Measures support underneath possession.",
        status="implemented",
    ),
    FeatureSpec(
        id="dropping_off_runs",
        domain="chance_creation",
        category="receiving",
        output_column="dropping_off_runs",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"associated_off_ball_run_subtype": "dropping_off"},
        description="Counts dropping-off runs.",
        interpretation="Measures movements creating passing outlets.",
        status="implemented",
    ),
    FeatureSpec(
        id="run_ahead_ball",
        domain="chance_creation",
        category="penetration",
        output_column="run_ahead_ball",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"associated_off_ball_run_subtype": "run_ahead_of_the_ball"},
        description="Counts runs ahead of the ball.",
        interpretation="Measures vertical penetration.",
        status="implemented",
    ),
    FeatureSpec(
        id="behind_runs",
        domain="chance_creation",
        category="penetration",
        output_column="behind_runs",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"associated_off_ball_run_subtype": "behind"},
        description="Counts runs behind the defense.",
        interpretation="Measures attempts to attack space behind defenders.",
        status="implemented",
    ),
    FeatureSpec(
        id="half_space_runs",
        domain="chance_creation",
        category="penetration",
        output_column="half_space_runs",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"associated_off_ball_run_subtype": "pulling_half_space"},
        description="Counts runs into the half-space.",
        interpretation="Measures occupation of interior attacking channels.",
        status="implemented",
    ),
    FeatureSpec(
        id="wide_runs",
        domain="chance_creation",
        category="penetration",
        output_column="wide_runs",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"associated_off_ball_run_subtype": "pulling_wide"},
        description="Counts runs toward wide areas.",
        interpretation="Measures width creation during attacks.",
        status="implemented",
    ),
]
