from feature_engine.specification import FeatureSpec


POSSESSION_FEATURES = [
    FeatureSpec(
        id="build_up_possessions",
        domain="possession",
        category="phase",
        output_column="build_up_possessions",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "build_up",
        },
        description="Counts build-up possession phases.",
        interpretation="Measures structured possession beginning from deeper areas.",
        status="implemented",
    ),
    FeatureSpec(
        id="create_phase_possessions",
        domain="possession",
        category="phase",
        output_column="create_phase_possessions",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "create",
        },
        description="Counts chance creation possession phases.",
        interpretation="Measures sustained attacking construction.",
        status="implemented",
    ),
    FeatureSpec(
        id="finish_phase_possessions",
        domain="possession",
        category="phase",
        output_column="finish_phase_possessions",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "finish",
        },
        description="Counts finishing possession phases.",
        interpretation="Measures possessions reaching finishing situations.",
        status="implemented",
    ),
    FeatureSpec(
        id="set_play_possessions",
        domain="possession",
        category="phase",
        output_column="set_play_possessions",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "set_play",
        },
        description="Counts set-play possession phases.",
        interpretation="Measures attacking possessions originating from restarts.",
        status="implemented",
    ),
    FeatureSpec(
        id="build_up_forward_progressions",
        domain="possession",
        category="progression",
        output_column="build_up_forward_progressions",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "build_up",
            "trajectory_direction": "forward",
        },
        description="Counts forward trajectories during build-up.",
        interpretation="Measures vertical progression while building attacks.",
        status="implemented",
    ),
    FeatureSpec(
        id="build_up_middle_third",
        domain="possession",
        category="territory",
        output_column="build_up_middle_third",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "build_up",
            "third_end": "middle_third",
        },
        description="Counts build-up possessions ending in the middle third.",
        interpretation="Measures midfield progression during build-up.",
        status="implemented",
    ),
    FeatureSpec(
        id="build_up_attacking_third",
        domain="possession",
        category="territory",
        output_column="build_up_attacking_third",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "build_up",
            "third_end": "attacking_third",
        },
        description="Counts build-up possessions reaching the attacking third.",
        interpretation="Measures successful territorial advancement from build-up.",
        status="implemented",
    ),
    FeatureSpec(
        id="successful_passes",
        domain="possession",
        category="passing",
        output_column="successful_passes",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "pass_outcome": "successful",
        },
        description="Counts successful passes.",
        interpretation="Measures passing execution.",
        status="implemented",
    ),
    FeatureSpec(
        id="forward_passes",
        domain="possession",
        category="passing",
        output_column="forward_passes",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "pass_direction": "forward",
        },
        description="Counts forward passes.",
        interpretation="Measures attacking intent through passing direction.",
        status="implemented",
    ),
    FeatureSpec(
        id="long_passes",
        domain="possession",
        category="passing",
        output_column="long_passes",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "pass_range": "long",
        },
        description="Counts long passes.",
        interpretation="Measures long-range passing tendencies.",
        status="implemented",
    ),
]
