from feature_engine.specification import FeatureSpec


PRESSURE_FEATURES = [
    FeatureSpec(
        id="pressure_events",
        domain="pressure",
        category="pressing",
        output_column="pressure_events",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"event_subtype": "pressure"},
        description="Counts pressure events.",
        interpretation="Measures overall defensive pressure activity.",
        status="implemented",
    ),
    FeatureSpec(
        id="pressing_events",
        domain="pressure",
        category="pressing",
        output_column="pressing_events",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"event_subtype": "pressing"},
        description="Counts pressing events.",
        interpretation="Measures active pressing actions.",
        status="implemented",
    ),
    FeatureSpec(
        id="counter_press_events",
        domain="pressure",
        category="counter_press",
        output_column="counter_press_events",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"event_subtype": "counter_press"},
        description="Counts counter-press actions.",
        interpretation="Measures immediate pressure after losing possession.",
        status="implemented",
    ),
    FeatureSpec(
        id="recovery_press_events",
        domain="pressure",
        category="recovery",
        output_column="recovery_press_events",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"event_subtype": "recovery_press"},
        description="Counts recovery press actions.",
        interpretation="Measures attempts to regain possession through pressing.",
        status="implemented",
    ),
    FeatureSpec(
        id="pressure_regains",
        domain="pressure",
        category="pressing_outcomes",
        output_column="pressure_regains",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"pressing_chain_end_type": "regain"},
        description="Counts pressing sequences ending in a regain.",
        interpretation="Measures successful pressing outcomes.",
        status="implemented",
    ),
    FeatureSpec(
        id="pressure_disruptions",
        domain="pressure",
        category="pressing_outcomes",
        output_column="pressure_disruptions",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={"pressing_chain_end_type": "disruption"},
        description="Counts pressing sequences ending in disruption.",
        interpretation="Measures disruptive defensive pressure.",
        status="implemented",
    ),
    FeatureSpec(
        id="high_block_pressure",
        domain="pressure",
        category="defensive_structure",
        output_column="high_block_pressure",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_out_of_possession_phase_type": "high_block",
        },
        description="Counts high-block defensive phases.",
        interpretation="Measures aggressive defensive positioning.",
        status="implemented",
    ),
    FeatureSpec(
        id="medium_block_pressure",
        domain="pressure",
        category="defensive_structure",
        output_column="medium_block_pressure",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_out_of_possession_phase_type": "medium_block",
        },
        description="Counts medium-block defensive phases.",
        interpretation="Measures balanced defensive organization.",
        status="implemented",
    ),
    FeatureSpec(
        id="low_block_pressure",
        domain="pressure",
        category="defensive_structure",
        output_column="low_block_pressure",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_out_of_possession_phase_type": "low_block",
        },
        description="Counts low-block defensive phases.",
        interpretation="Measures deep defensive organization.",
        status="implemented",
    ),
    FeatureSpec(
        id="attacking_third_pressing",
        domain="pressure",
        category="field_pressure",
        output_column="attacking_third_pressing",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "event_subtype": "pressing",
            "third_end": "attacking_third",
        },
        description="Counts pressing actions occurring in the attacking third.",
        interpretation="Measures high pressing in advanced areas.",
        status="implemented",
    ),
]
