from feature_engine.specification import FeatureSpec


PROGRESSION_FEATURES = [
    FeatureSpec(
        id="progression_first_line_breaks",
        domain="progression",
        category="line_breaks",
        output_column="progression_first_line_breaks",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "first_line_break_type": ["through", "around"],
        },
        description="Counts first defensive line breaks.",
        interpretation="Higher values indicate the ability to progress beyond the first defensive line.",
        status="implemented",
    ),
    FeatureSpec(
        id="progression_first_line_break_through",
        domain="progression",
        category="line_breaks",
        output_column="progression_first_line_break_through",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "first_line_break_type": "through",
        },
        description="Counts through first-line breaks.",
        interpretation="Measures vertical progression through the first defensive line.",
        status="implemented",
    ),
    FeatureSpec(
        id="progression_first_line_break_around",
        domain="progression",
        category="line_breaks",
        output_column="progression_first_line_break_around",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "first_line_break_type": "around",
        },
        description="Counts around first-line breaks.",
        interpretation="Measures progression around the first defensive line.",
        status="implemented",
    ),
    FeatureSpec(
        id="progression_second_line_breaks",
        domain="progression",
        category="line_breaks",
        output_column="progression_second_line_breaks",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "second_last_line_break_type": ["through", "around"],
        },
        description="Counts second defensive line breaks.",
        interpretation="Higher values indicate progression into advanced attacking areas.",
        status="implemented",
    ),
    FeatureSpec(
        id="progression_second_line_break_through",
        domain="progression",
        category="line_breaks",
        output_column="progression_second_line_break_through",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "second_last_line_break_type": "through",
        },
        description="Counts through second-line breaks.",
        interpretation="Measures vertical progression through the second defensive line.",
        status="implemented",
    ),
    FeatureSpec(
        id="progression_second_line_break_around",
        domain="progression",
        category="line_breaks",
        output_column="progression_second_line_break_around",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "second_last_line_break_type": "around",
        },
        description="Counts around second-line breaks.",
        interpretation="Measures progression around the second defensive line.",
        status="implemented",
    ),
    FeatureSpec(
        id="progression_last_line_breaks",
        domain="progression",
        category="line_breaks",
        output_column="progression_last_line_breaks",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "last_line_break_type": ["through", "around"],
        },
        description="Counts final defensive line breaks.",
        interpretation="Higher values indicate entries behind the defensive line.",
        status="implemented",
    ),
    FeatureSpec(
        id="progression_last_line_break_through",
        domain="progression",
        category="line_breaks",
        output_column="progression_last_line_break_through",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "last_line_break_type": "through",
        },
        description="Counts through final-line breaks.",
        interpretation="Measures penetration directly through the final defensive line.",
        status="implemented",
    ),
    FeatureSpec(
        id="progression_last_line_break_around",
        domain="progression",
        category="line_breaks",
        output_column="progression_last_line_break_around",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "last_line_break_type": "around",
        },
        description="Counts around final-line breaks.",
        interpretation="Measures penetration around the final defensive line.",
        status="implemented",
    ),
    FeatureSpec(
        id="progression_forward_trajectories",
        domain="progression",
        category="trajectory",
        output_column="progression_forward_trajectories",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "trajectory_direction": "forward",
        },
        description="Counts forward trajectories.",
        interpretation="Higher values indicate direct forward progression.",
        status="implemented",
    ),
]
