from feature_engine.specification import FeatureSpec


SET_PIECE_FEATURES = [
    FeatureSpec(
        id="throw_in_for",
        domain="set_pieces",
        category="throw_ins",
        output_column="throw_in_for",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "game_interruption_before": "throw_in_for",
        },
        description="Counts attacking throw-ins awarded.",
        interpretation="Measures attacking throw-in opportunities.",
        status="implemented",
    ),
    FeatureSpec(
        id="throw_in_against",
        domain="set_pieces",
        category="throw_ins",
        output_column="throw_in_against",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "game_interruption_before": "throw_in_against",
        },
        description="Counts throw-ins conceded.",
        interpretation="Measures defensive throw-in situations.",
        status="implemented",
    ),
    FeatureSpec(
        id="corner_for",
        domain="set_pieces",
        category="corners",
        output_column="corner_for",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "game_interruption_before": "corner_for",
        },
        description="Counts attacking corners.",
        interpretation="Measures corner kick opportunities.",
        status="implemented",
    ),
    FeatureSpec(
        id="corner_against",
        domain="set_pieces",
        category="corners",
        output_column="corner_against",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "game_interruption_before": "corner_against",
        },
        description="Counts corners conceded.",
        interpretation="Measures defensive corner situations.",
        status="implemented",
    ),
    FeatureSpec(
        id="free_kick_for",
        domain="set_pieces",
        category="free_kicks",
        output_column="free_kick_for",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "game_interruption_before": "free_kick_for",
        },
        description="Counts attacking free kicks.",
        interpretation="Measures offensive free-kick opportunities.",
        status="implemented",
    ),
    FeatureSpec(
        id="free_kick_against",
        domain="set_pieces",
        category="free_kicks",
        output_column="free_kick_against",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "game_interruption_before": "free_kick_against",
        },
        description="Counts defensive free kicks.",
        interpretation="Measures free kicks conceded.",
        status="implemented",
    ),
    FeatureSpec(
        id="goal_kick_for",
        domain="set_pieces",
        category="goal_kicks",
        output_column="goal_kick_for",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "game_interruption_before": "goal_kick_for",
        },
        description="Counts attacking goal kicks.",
        interpretation="Measures possession restarts from goal kicks.",
        status="implemented",
    ),
    FeatureSpec(
        id="goal_kick_against",
        domain="set_pieces",
        category="goal_kicks",
        output_column="goal_kick_against",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "game_interruption_before": "goal_kick_against",
        },
        description="Counts opponent goal kicks.",
        interpretation="Measures opportunities to press opponent restarts.",
        status="implemented",
    ),
    FeatureSpec(
        id="goal_for",
        domain="set_pieces",
        category="goals",
        output_column="goal_for",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "game_interruption_after": "goal_for",
        },
        description="Counts goals scored following an event.",
        interpretation="Measures scoring outcomes recorded in the event stream.",
        status="implemented",
    ),
    FeatureSpec(
        id="goal_against",
        domain="set_pieces",
        category="goals",
        output_column="goal_against",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "game_interruption_after": "goal_against",
        },
        description="Counts goals conceded following an event.",
        interpretation="Measures defensive outcomes resulting in goals against.",
        status="implemented",
    ),
]
