from feature_engine.specification import FeatureSpec


TERRITORY_FEATURES = [
    FeatureSpec(
        id="territory_attacking_third_engagements",
        domain="territory",
        category="territorial_control",
        output_column="territory_attacking_third_engagements",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "event_type": "on_ball_engagement",
            "third_end": "attacking_third",
        },
        description="Counts on-ball engagements ending in the attacking third.",
        interpretation="Higher values indicate sustained territorial occupation in advanced areas.",
        status="implemented",
    ),
    FeatureSpec(
        id="territory_middle_third_engagements",
        domain="territory",
        category="territorial_control",
        output_column="territory_middle_third_engagements",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "event_type": "on_ball_engagement",
            "third_end": "middle_third",
        },
        description="Counts on-ball engagements ending in the middle third.",
        interpretation="Higher values indicate prolonged midfield control and circulation.",
        status="implemented",
    ),
    FeatureSpec(
        id="territory_defensive_third_engagements",
        domain="territory",
        category="territorial_control",
        output_column="territory_defensive_third_engagements",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "event_type": "on_ball_engagement",
            "third_end": "defensive_third",
        },
        description="Counts on-ball engagements ending in the defensive third.",
        interpretation="Higher values indicate defensive territorial occupation.",
        status="implemented",
    ),
    FeatureSpec(
        id="territory_center_channel_engagements",
        domain="territory",
        category="channels",
        output_column="territory_center_channel_engagements",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "event_type": "on_ball_engagement",
            "channel_end": "center",
        },
        description="Counts on-ball engagements ending in the central channel.",
        interpretation="Higher values indicate central occupation during possession.",
        status="implemented",
    ),
    FeatureSpec(
        id="territory_left_half_space_engagements",
        domain="territory",
        category="channels",
        output_column="territory_left_half_space_engagements",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "event_type": "on_ball_engagement",
            "channel_end": "half_space_left",
        },
        description="Counts on-ball engagements ending in the left half-space.",
        interpretation="Higher values indicate tactical use of the left interior channel.",
        status="implemented",
    ),
    FeatureSpec(
        id="territory_right_half_space_engagements",
        domain="territory",
        category="channels",
        output_column="territory_right_half_space_engagements",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "event_type": "on_ball_engagement",
            "channel_end": "half_space_right",
        },
        description="Counts on-ball engagements ending in the right half-space.",
        interpretation="Higher values indicate tactical use of the right interior channel.",
        status="implemented",
    ),
    FeatureSpec(
        id="territory_left_wide_engagements",
        domain="territory",
        category="channels",
        output_column="territory_left_wide_engagements",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "event_type": "on_ball_engagement",
            "channel_end": "wide_left",
        },
        description="Counts on-ball engagements ending on the left flank.",
        interpretation="Higher values indicate wider left-sided attacking structure.",
        status="implemented",
    ),
    FeatureSpec(
        id="territory_right_wide_engagements",
        domain="territory",
        category="channels",
        output_column="territory_right_wide_engagements",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "event_type": "on_ball_engagement",
            "channel_end": "wide_right",
        },
        description="Counts on-ball engagements ending on the right flank.",
        interpretation="Higher values indicate wider right-sided attacking structure.",
        status="implemented",
    ),
    FeatureSpec(
        id="territory_attacking_third_possessions",
        domain="territory",
        category="possession",
        output_column="territory_attacking_third_possessions",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "event_type": "player_possession",
            "third_end": "attacking_third",
        },
        description="Counts player possessions ending in the attacking third.",
        interpretation="Higher values indicate sustained attacking possession.",
        status="implemented",
    ),
    FeatureSpec(
        id="territory_middle_third_possessions",
        domain="territory",
        category="possession",
        output_column="territory_middle_third_possessions",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "event_type": "player_possession",
            "third_end": "middle_third",
        },
        description="Counts player possessions ending in the middle third.",
        interpretation="Higher values indicate extended midfield possession phases.",
        status="implemented",
    ),
]
