from feature_engine.specification import FeatureSpec


TRANSITION_FEATURES = [
    FeatureSpec(
        id="transition_attacking_transitions",
        domain="transition",
        category="attacking_transition",
        output_column="transition_attacking_transitions",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "transition",
        },
        description="Counts attacking transition phases.",
        interpretation="Higher values indicate more attacking transition opportunities.",
        status="implemented",
    ),
    FeatureSpec(
        id="transition_quick_breaks",
        domain="transition",
        category="attacking_transition",
        output_column="transition_quick_breaks",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "quick_break",
        },
        description="Counts quick-break possessions.",
        interpretation="Higher values indicate faster attacking transitions.",
        status="implemented",
    ),
    FeatureSpec(
        id="transition_direct_play",
        domain="transition",
        category="attacking_transition",
        output_column="transition_direct_play",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "direct",
        },
        description="Counts direct attacking phases.",
        interpretation="Higher values indicate a more direct transition style.",
        status="implemented",
    ),
    FeatureSpec(
        id="transition_defending_transition",
        domain="transition",
        category="defensive_transition",
        output_column="transition_defending_transition",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_out_of_possession_phase_type": "defending_transition",
        },
        description="Counts defensive transition phases.",
        interpretation="Measures defensive organization during opponent transitions.",
        status="implemented",
    ),
    FeatureSpec(
        id="transition_defending_direct",
        domain="transition",
        category="defensive_transition",
        output_column="transition_defending_direct",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_out_of_possession_phase_type": "defending_direct",
        },
        description="Counts defending-direct phases.",
        interpretation="Measures defending against direct attacks.",
        status="implemented",
    ),
    FeatureSpec(
        id="transition_defending_quick_break",
        domain="transition",
        category="defensive_transition",
        output_column="transition_defending_quick_break",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_out_of_possession_phase_type": "defending_quick_break",
        },
        description="Counts defending quick-break situations.",
        interpretation="Measures defending against fast attacking transitions.",
        status="implemented",
    ),
    FeatureSpec(
        id="transition_disruption",
        domain="transition",
        category="disruption",
        output_column="transition_disruption",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "disruption",
        },
        description="Counts disruption phases.",
        interpretation="Higher values indicate interrupted attacking sequences.",
        status="implemented",
    ),
    FeatureSpec(
        id="transition_chaotic",
        domain="transition",
        category="disruption",
        output_column="transition_chaotic",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "chaotic",
        },
        description="Counts chaotic attacking phases.",
        interpretation="Measures play occurring in unstable transition states.",
        status="implemented",
    ),
    FeatureSpec(
        id="transition_forward_progressions",
        domain="transition",
        category="progression",
        output_column="transition_forward_progressions",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "transition",
            "trajectory_direction": "forward",
        },
        description="Counts forward transitions.",
        interpretation="Measures forward progression during transition phases.",
        status="implemented",
    ),
    FeatureSpec(
        id="transition_line_breaks",
        domain="transition",
        category="progression",
        output_column="transition_line_breaks",
        source_table="fact_dynamic_events",
        group_by=("match_id", "team_id"),
        aggregation="count",
        source_column=None,
        filters={
            "team_in_possession_phase_type": "transition",
            "furthest_line_break_type": [
                "through",
                "around",
            ],
        },
        description="Counts transition possessions that break defensive lines.",
        interpretation="Measures the effectiveness of attacking transitions at penetrating defensive structures.",
        status="implemented",
    ),
]
